fix r8169 depends of 5.x

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,11 +32,24 @@ jobs:
     strategy:
       matrix:
         include:
+          - version: 6.2 
+            platform: geminilake
+          - version: 6.2 
+            platform: v1000 
+
           - version: 7.1
             platform: epyc7002
-   
+          - version: 7.1 
+            platform: geminilake
+          - version: 7.1
+            platform: v1000
+
           - version: 7.2
             platform: epyc7002
+          - version: 7.2 
+            platform: geminilake
+          - version: 7.2
+            platform: v1000
 
     runs-on: ubuntu-latest
 
@@ -148,20 +161,101 @@ jobs:
           sudo cp -a ${ROOT_PATH}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/source/output ${ROOT_PATH}/source/
           sudo chmod a+rw -R ${ROOT_PATH}/source/output
     
+      # - name: GCC 12
+      #   if: startsWith(env.CCVER, '12') && startsWith(env.KVER, '4')
+      #   shell: python
+      #   run: |
+      #     # -*- coding: utf-8 -*-
+      # 
+      #     import sys, os, re
+      # 
+      #     # R_X86_64_PC32  = 2
+      #     # R_X86_64_PLT32 = 4
+      # 
+      #     def PLT322PC32(infile, outfile):
+      #         readelfLines = []
+      #         with os.popen('readelf -r "{}"'.format(infile)) as f:
+      #             readelfLines = f.readlines()
+      # 
+      #         offsetList = []
+      #         start = 0
+      #         for idx, line in enumerate(readelfLines):
+      #             if line.startswith('Relocation section'):
+      #                 arr = re.findall(r'0x[0-9a-f]*', line)
+      #                 offat = int(arr[0], base=16)
+      #                 start = idx + 1
+      #                 continue
+      #             if "R_X86_64_PLT32" in line:
+      #                 offsetList.append(offat + (idx - start - 1) * 24 + 8)
+      # 
+      #         if len(offsetList) > 0:
+      #             obj = []
+      #             with open(infile, 'rb') as f:
+      #                 obj = list(f.read())
+      # 
+      #             if len(obj) > 0:
+      #                 for offset in offsetList:
+      #                     assert obj[offset] == (4 if sys.version_info.major >= 3 else 'x04')
+      #                     obj[offset] = 2 if sys.version_info.major >= 3 else 'x02'
+      #         
+      #             with open(outfile, 'wb') as f:
+      #                 f.write(bytes(obj) if sys.version_info.major >= 3 else ''.join(obj))
+      #             return True
+      #         return False
+      # 
+      #     if __name__ == '__main__':
+      #         ROOT_PATH = '${{ github.workspace }}'
+      #         modules = os.listdir(os.path.join(ROOT_PATH, 'source/output'))
+      #         for module in modules:
+      #             module_path = os.path.join(ROOT_PATH, 'source/output', module)
+      #             ret = PLT322PC32(module_path, module_path)
+      #             if ret == False:
+      #                 print('{} no has.'.format(module_path))
+
       - name: Tar to Artifacts
         run: |
-          OFFICIAL_PATH="${{ github.workspace }}/official/${{ matrix.platform }}-${{ env.KVER }}"
+          if [ "${{ matrix.platform }}" = "epyc7002" ]; then
+            OFFICIAL_PATH="${{ github.workspace }}/official/hda1/${{ matrix.platform }}-${{ matrix.version }}-${{ env.KVER }}"
+          else
+            OFFICIAL_PATH="${{ github.workspace }}/official/hda1/${{ matrix.platform }}-${{ env.KVER }}"
+          fi
           PARTY3RD_PATH="${{ github.workspace }}/thirdparty/${{ matrix.platform }}-${{ env.KVER }}"
 
-          # echo "copy official modules"
-          # for M in `ls ${{ github.workspace }}/source/output`; do
-          #   [ -f ${OFFICIAL_PATH}/${M} ] && cp -f ${OFFICIAL_PATH}/${M} "${{ github.workspace }}/source/output"
-          # done
+          echo "copy official modules"
+          OM=(cpufreq_performance i915 processor ehci-hcd ehci-pci uhci-hcd xhci-hcd xhci-pci)
+          for M in ${OM[@]}; do
+            function _copydepends() {
+              [ -f "${OFFICIAL_PATH}/${1}" ] && [ ! -f "${OFFICIAL_PATH/hda1/rd}/${1}" ] && cp -f "${OFFICIAL_PATH}/${1}" "${{ github.workspace }}/source/output"
+              depends=($(modinfo "${OFFICIAL_PATH}/${1}" | grep depends: | awk -F: '{print $2}' | awk '$1=$1' | sed 's/,/ /g'))
+              if [ ${#depends[*]} -gt 0 ]; then
+                for k in ${depends[@]}; do
+                  _copydepends "${k}.ko"
+                done
+              fi
+            }
+            _copydepends "${M}.ko"
+          done
 
           echo "copy 3rd modules"
           [ -d "${PARTY3RD_PATH}" ] && cp -rf "${PARTY3RD_PATH}/." "${{ github.workspace }}/source/output"
 
-          tar caf ${{ github.workspace }}/source/${{ matrix.platform }}-${{ matrix.version }}-${{ env.KVER }}.tgz -C ${{ github.workspace }}/source/output .
+          echo "check depends"
+          for M in `ls ${{ github.workspace }}/source/output`; do
+            depends=(`modinfo "${{ github.workspace }}/source/output/${M}" | grep depends: | awk -F: '{print $2}' | awk '$1=$1' | sed 's/,/ /g'`)
+            if [ ${#depends[*]} -gt 0 ]; then
+              for k in ${depends[@]}; do
+                if [ ! -f "${{ github.workspace }}/source/output/${k}.ko" ]; then
+                  [ -f "${OFFICIAL_PATH}/${k}.ko" ] && FLAG=O || FLAG=X
+                  echo "[W][${FLAG}] '${{ matrix.platform }}-${{ env.KVER }}' - '${M}' depends '${k}' does not exist."
+                fi
+              done
+            fi
+          done
+          if [ "${{ matrix.platform }}" = "epyc7002" ]; then
+            tar caf ${{ github.workspace }}/source/${{ matrix.platform }}-${{ matrix.version }}-${{ env.KVER }}.tgz -C ${{ github.workspace }}/source/output .
+          else
+            tar caf ${{ github.workspace }}/source/${{ matrix.platform }}-${{ env.KVER }}.tgz -C ${{ github.workspace }}/source/output .
+          fi
 
       - name: Upload to Artifacts
         uses: actions/upload-artifact@v3
@@ -175,3 +269,100 @@ jobs:
           sudo rm -rf ${{ github.workspace }}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/source/*
 
 
+  firmware:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout
+        uses: actions/checkout@main
+
+      - name: download to artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: modules
+          path: ./modules
+
+      - name: firmware
+        run: |
+          mkdir -p firmware
+
+          echo "copy 3rd modules"
+          PARTY3RD_PATH="${{ github.workspace }}/thirdparty/firmware"
+          cp -rf ${PARTY3RD_PATH}/* firmware/
+
+          echo "extract all modules"
+          for F in ./modules/*.tgz; do mkdir "${F%.tgz}" && tar -xzf "${F}" -C "${F%.tgz}"; done
+          
+          echo "get firmware"
+          SOURCE=/tmp/linux-firmware
+          git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git ${SOURCE}
+          while read L; do
+            if [ -e "${SOURCE}/${L}" ]; then
+              mkdir -p "`dirname firmware/${L}`"
+              cp "${SOURCE}/${L}" "firmware/${L}"
+            else
+              [ -e "firmware/${L}" ] && echo "Used thirdparty ${L}" || echo "Missing ${L}"
+            fi
+          done < <(find ./modules -name \*.ko -exec sh -c '/sbin/modinfo {} | grep ^firmware' \; | awk '{print $2}')
+
+          tar caf firmware.tgz -C firmware .
+
+
+      - name: Upload to Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: modules
+          path: |
+            firmware.tgz
+
+
+  release:
+    runs-on: ubuntu-latest
+    needs: firmware
+    steps:
+      - name: Checkout
+        uses: actions/checkout@main
+
+      - name: Calculate version
+        run: |
+          # Calculate version
+          VERSION=""
+          if [ ${{ github.event_name }} == 'release' -a ${{ github.ref_type }} == 'tag' ]; then
+            VERSION="${{ github.ref_name }}"
+          elif [ -n "${{ inputs.version }}" ]; then
+            if [ "`echo ${{ inputs.version }} | cut -d '.' -f 1,2`" = "`date +'%y.%-m'`" ]; then
+              VERSION="${{ inputs.version }}"
+            else
+              LATEST_TAG="`curl -skL "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name" 2>/dev/null`"
+              if [ -n "${LATEST_TAG}" -a "`echo ${LATEST_TAG} | cut -d '.' -f 1,2`" = "`date +'%y.%-m'`" ]; then  # format %y.%-m.$i
+                VERSION="`echo ${LATEST_TAG} | awk -F '.' '{$3=$3+1}1' OFS='.'`"
+              else
+                VERSION="`date +'%y.%-m'`.0"
+              fi
+            fi
+          else
+            VERSION=""
+          fi
+
+          echo "VERSION: ${VERSION}"
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
+
+      - name: download to artifacts
+        if: env.VERSION != ''
+        uses: actions/download-artifact@v3
+        with:
+          name: modules
+          path: ./modules
+
+      - name: Zip modules
+        if: env.VERSION != ''
+        run: |
+          echo "${{ env.VERSION }}" > "modules/VERSION"
+          zip -9 modules.zip -j modules/*
+
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        if: env.VERSION != ''
+        with:
+          tag_name: ${{ env.VERSION }}
+          files: modules.zip
